<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NavigationSource Condition="'$(NavigationSource)' == ''">../../Navigation/HybridLocal/MainPage.cs</NavigationSource>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(NavigationSource)" Link="MainPage.cs" />
  </ItemGroup>
</Project>
