<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<WindowsPackageType Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">MSIX</WindowsPackageType>
		<RootNamespace>HybridApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<NoWarn>0028</NoWarn>
		<Optimize>false</Optimize>

		<!-- Display name -->
		<ApplicationTitle>Wisej.NET</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.iceteagroup.hybrid</ApplicationId>
		<ApplicationIdGuid>949865ae-c5be-4b08-b7b9-9d524800ddd4</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.2</ApplicationDisplayVersion>
		<ApplicationVersion>34</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0-ios'">
		<MtouchInterpreter>-all,Humanizer</MtouchInterpreter>
	</PropertyGroup>

  <PropertyGroup>
	<EnableAssemblyILStripping>false</EnableAssemblyILStripping>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	<MtouchLink>None</MtouchLink>
	<MtouchUseLlvm>False</MtouchUseLlvm>
	<UseInterpreter>true</UseInterpreter>
	<MtouchDebug>True</MtouchDebug>
	<Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	<MtouchUseLlvm>False</MtouchUseLlvm>
	<MtouchDebug>True</MtouchDebug>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	<PublishTrimmed>False</PublishTrimmed>
	<RunAOTCompilation>False</RunAOTCompilation>
	<DebugSymbols>False</DebugSymbols>
	<AndroidUseAapt2>False</AndroidUseAapt2>
	<Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	<AndroidUseAapt2>True</AndroidUseAapt2>
	<DebugSymbols>False</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net9.0-ios'">
    <CodesignKey>Apple Distribution: ICE TEA GROUP LLC (C5KB4U3BM9)</CodesignKey>
    <CodesignProvision></CodesignProvision>
    <ProvisioningType>manual</ProvisioningType>
  </PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
	  <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />

	  <!-- Splash Screen -->
	  <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#7000D2" BaseSize="456,456" />

	  <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FeaturesOffline\FeaturesOffline.csproj" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
    <PackageReference Include="Wisej-4-Hybrid" Version="4.0.14" ExcludeAssets="all" />
    <PackageReference Include="Wisej-4-Hybrid-Native" Version="4.0.14" ExcludeAssets="all" />
    <ProjectReference Include="$(HybridSourceRoot)Wisej.Hybrid.Native\Wisej.Hybrid.Native.csproj" />
    <ProjectReference Include="$(HybridExtensionsSourceRoot)Authentication\Wisej.Hybrid.Authentication.Native\Wisej.Hybrid.Authentication.Native.csproj" />
    <ProjectReference Include="$(HybridExtensionsSourceRoot)DocumentScanner\Wisej.Hybrid.DocumentScanner.Native\Wisej.Hybrid.DocumentScanner.Native.csproj" Condition="'$(TargetFramework)' != 'net9.0-windows10.0.19041.0'" />
    <ProjectReference Include="$(HybridExtensionsSourceRoot)MLKit\Wisej.Hybrid.MLKit.Native\Wisej.Hybrid.MLKit.Native.csproj" />
  </ItemGroup>
</Project>
