//
// Mixin Theme Definition
//
// Mixin theme files define only a subset of the theme and are overlayed
// on top of the loaded theme. A mixin theme can extend or override the loaded theme.
//
// Mixin themes are useful to refine or style a particular feature in an application and/or
// style a new component.
//
{
	"name": "NavigationMixin",

	"fonts": {
		"viewTitle": {
			"size": 32,
			"family": [ "Segoe UI", "Roboto", "Helvetica Neue", "Arial" ],
			"bold": true
		}
	}
}