name: .NET Publish Android and iOS on macOS

on:
  push:
    branches: [ main ] # Change this to the branch you want to trigger the action on
  pull_request:
    branches: [ main ] # Change this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Using .NET 8

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore Showcase/App

    - name: Publish Android project
      run: dotnet publish Showcase/App --configuration Release -f:net8.0-android --output ./publish/android # Using .NET 8 Android framework

    - name: Find and upload Android APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: ./publish/android/**/*.apk

    - name: Publish iOS project without code signing
      run: dotnet publish Showcase/App --configuration Release -f:net8.0-ios --output ./publish/ios -p:_DeviceName=:v2:runtime=iossimulator-arm64 -p:Codesign=false

    - name: Find and upload iOS IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-ipa
        path: ./publish/ios/**/*.ipa
